//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManager.BusinessLogic.Data.CaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictOfInterest
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int CaseId { get; set; }
        public System.DateTime DeclaredDate { get; set; }
        public int StaffDesignationId { get; set; }
        public bool IsReassignmentPending { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
