//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManager.BusinessLogic.Data.CaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
