//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManager.BusinessLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public string CaseNumber { get; set; }
        public int StatusId { get; set; }
        public int DepartmentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CaseStatus CaseStatus { get; set; }
    }
}
