//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManager.BusinessLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Username { get; set; }
        public string Name { get; set; }
        public int DesignationId { get; set; }
        public int DepartmentId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
